# Generated by Django 4.1.2 on 2022-10-24 19:07

import django.core.validators
from django.db import migrations, models
import my_music_app.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('PM', 'Pop Music'), ('JM', 'Jazz Music'), ('RBM', 'R&B Music'), ('RM', 'Rock Music'), ('CM', 'Country Music'), ('DM', 'Dance Music'), ('HHM', 'Hip Hop Music'), ('OM', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=15, validators=[my_music_app.web.models.user_name_validation, django.core.validators.MinLengthValidator(2)])),
                ('e_mail', models.EmailField(max_length=254)),
                ('user_age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
