# Generated by Django 4.1.2 on 2022-10-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_age',
            new_name='age',
        ),
    ]
